[package]
name = "Nizer LMT"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-cli-config = "~1.18"
solana-program = "~1.18"
solana-program-test = "~1.18"
solana-sdk = "~1.18"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]